#pragma once

#define MLIBC_SYSTEM_NAME "orange"
#define MLIBC_DEFAULT_LIBRARY_PATHS "/lib\n/lib64\n/usr/lib\n/usr/lib64"
#define MLIBC_NUM_DEFAULT_LIBRARY_PATHS 4
#define MLIBC_MAP_DSO_SEGMENTS 0
#define MLIBC_MMAP_ALLOCATE_DSO 0
#define MLIBC_MAP_FILE_WINDOWS 0
/* #undef MLIBC_STATIC_BUILD */
#define MLIBC_DEBUG_ALLOCATOR 0

